CREATE TABLE IF NOT EXISTS `ustam_analytics.jobs` (
  job_id INTEGER NOT NULL,
  title STRING NOT NULL,
  description STRING,
  category_id INTEGER NOT NULL,
  customer_id INTEGER NOT NULL,
  assigned_craftsman_id INTEGER,
  location STRING,
  city STRING,
  district STRING,
  latitude FLOAT,
  longitude FLOAT,
  budget_min NUMERIC,
  budget_max NUMERIC,
  final_price NUMERIC,
  urgency STRING,
  status STRING,
  preferred_date DATE,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  completed_at TIMESTAMP,
  view_count INTEGER,
  quote_count INTEGER
);